steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'package']
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'eu.gcr.io/$PROJECT_ID/tech-radar:$(node -p -e “require(‘./package.json’).version”)', '.' ]
images:
  - 'eu.gcr.io/$PROJECT_ID/tech-radar:$(node -p -e “require(‘./package.json’).version”)'
